kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080  # App
    hostPort: 8080
    protocol: TCP
  - containerPort: 30090  # Prometheus
    hostPort: 9090
    protocol: TCP
  - containerPort: 30300  # Grafana
    hostPort: 3000
    protocol: TCP
  kubeadmConfigPatches:
  - |
    kind: KubeletConfiguration
    evictionHard:
      memory.available: "200Mi"
