apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: autoscale-demo-load-test
  labels:
    app: k6
spec:
  parallelism: 1
  script:
    configMap:
      name: k6-load-test-script
      file: test.js
  separate: false
  # Enable Prometheus metrics output with remote write URL
  arguments: --out experimental-prometheus-rw --env K6_PROMETHEUS_RW_SERVER_URL=http://prometheus-operated:9090/api/v1/write
  cleanup: 'post'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-load-test-script
data:
  test.js: |
    import http from 'k6/http';
    import { sleep, check } from 'k6';

    export const options = {
      stages: [
        // Gradual ramp-up: 0 to 50 users over 30 seconds
        { duration: '30', target: 50 },
        // Steady load for 1 minute
        { duration: '1m', target: 50 },
        // Increase to peak: 50 to 200 users over 2 minutes
        { duration: '1m', target: 200 },
        // Sustain peak load for 2 minutes
        { duration: '30m', target: 200 },
        // Gradual ramp-down over 30 seconds
        { duration: '30s', target: 0 },
      ],
      thresholds: {
        http_req_failed: ['rate<0.01'], // HTTP errors should be less than 1%
        http_req_duration: ['p(95)<500'], // 95% of requests should be below 500ms
      },
    };

    export default function() {
      // Randomize the CPU load duration and intensity to create more realistic patterns
      const duration = Math.floor(Math.random() * 3) + 1; // 1-3 seconds
      const intensity = Math.floor(Math.random() * 30) + 60; // 60-90% intensity
      
      const response = http.get(`http://autoscale-demo:80/api/cpu-load?durationSeconds=${duration}&intensity=${intensity}`);
      
      // Validate the response
      check(response, {
        'status was 200': (r) => r.status === 200,
        'response contains expected text': (r) => r.body.includes('CPU load completed'),
      });
      
      // Add randomized sleep to simulate real user behavior
      sleep(Math.random() * 2 + 1); // 1-3 seconds
    }
